Add solution for dz3-tooltip task
js-tasks-ru/htmlcss-20240614_dkalabukhov pull request #10
Opened 2024-07-04 13:02 UTC by dkalabukhov

2024-07-04 13:03 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-07-05 12:45 UTC, GSemikozov requested changes

2024-07-05 12:45 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  text-align: center;
нет, это принципиально inlin-block, и тогда center не надо

2024-07-05 12:45 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  margin: auto 0;
лишнее

2024-07-10 17:14 UTC, dkalabukhov commented on 05-lection3/01-tooltip/tooltip.css
> +  text-align: center;
Сделал элемент инлайн-блоком

2024-07-10 17:14 UTC, dkalabukhov commented on 05-lection3/01-tooltip/tooltip.css
> +  margin: auto 0;
Убрал

2024-07-12 14:03 UTC, GSemikozov approved these changes

2024-07-12 14:03 UTC, merged