Dz5 checkbox
js-tasks-ru/htmlcss-20240614_dkalabukhov pull request #15
Opened 2024-07-19 14:47 UTC by dkalabukhov

2024-07-19 14:47 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-07-19 15:50 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-07-19 15:52 UTC, GSemikozov requested changes

2024-07-19 15:52 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox_disabled {
.checkbox__input:disabled ...

2024-07-19 15:52 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox_disabled {
класс блока будет дублировать нативный функционал, в нем нет смысла

2024-07-19 15:52 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +  cursor: pointer
`;`

2024-07-22 13:29 UTC, dkalabukhov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox_disabled {
Исправил

2024-07-22 13:29 UTC, dkalabukhov commented on 07-lection5/01-checkbox/checkbox.css
> +  cursor: pointer
Более не актуально

2024-07-27 14:33 UTC, GSemikozov approved these changes

2024-07-27 14:33 UTC, merged