Solution for dz4-responsive-homepage task
js-tasks-ru/htmlcss-20240614_dkalabukhov pull request #18
Opened 2024-07-22 15:17 UTC by dkalabukhov

2024-07-22 15:17 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-07-24 19:19 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-07-27 14:37 UTC, GSemikozov requested changes

2024-07-27 14:37 UTC, GSemikozov commented on components/footer/footer.css
> +    padding-left: 16px;
лучше на уровне контейнера добавить

2024-07-27 14:37 UTC, GSemikozov commented on components/header/header.css
> +    padding-left: 30px;
и тогда не придется фантазировать в разных местах про одно и то же)

2024-07-27 14:37 UTC, GSemikozov commented on components/mainly/mainly.css
> +  grid-template-rows: repeat(2, minmax(367px, auto));
это лишнее, minmax + auto-fill нам подходит для темплейта колонок

2024-07-28 14:46 UTC, dkalabukhov commented on components/footer/footer.css
> +    padding-left: 16px;
Исправил

2024-07-28 14:46 UTC, dkalabukhov commented on components/header/header.css
> +    padding-left: 30px;
Исправил

2024-07-28 14:47 UTC, dkalabukhov commented on components/mainly/mainly.css
> +  grid-template-rows: repeat(2, minmax(367px, auto));
Сделал  так: 
grid-template-rows: repeat(auto-fill, minmax(367px, auto));
 grid-auto-rows: minmax(367px, auto);

2024-08-01 21:50 UTC, GSemikozov requested changes

2024-08-01 21:50 UTC, GSemikozov commented on components/mainly/mainly.css
> +  grid-template-rows: repeat(auto-fill, minmax(367px, auto));
а зачем так делать если ниже есть grid-auto-rows?)

2024-09-10 13:21 UTC, GSemikozov requested changes

2024-09-10 13:21 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  transform: translateY(28px);
ненадежно, лучше уже через контекст и класс-микс задавать нужные значения для позиционирования

2024-09-13 17:59 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-09-16 15:30 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-09-16 15:31 UTC, dkalabukhov commented on 05-lection3/01-tooltip/tooltip.css
> +  transform: translateY(28px);
Оставил, обсудили в дискорде

2024-09-17 12:19 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-09-17 12:56 UTC, GSemikozov approved these changes

2024-09-17 12:57 UTC, merged