Solution for dz5-input task
js-tasks-ru/htmlcss-20240614_dkalabukhov pull request #20
Opened 2024-07-25 16:04 UTC by dkalabukhov

2024-07-25 16:04 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-07-27 14:39 UTC, GSemikozov requested changes

2024-07-27 14:39 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <label class="input">
а вот в случае с инпутом все заворачивать в лейбл не надо

2024-07-27 14:39 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                <div class="input__title">Label</div>
вот это - label

2024-07-28 16:12 UTC, dkalabukhov commented on 07-lection5/04-input/index.html
> +            <label class="input">
Исправил

2024-07-28 16:12 UTC, dkalabukhov commented on 07-lection5/04-input/index.html
> +                <div class="input__title">Label</div>
Исправил

2024-08-01 21:51 UTC, GSemikozov approved these changes

2024-08-01 21:51 UTC, merged