Added changing theme functionality, added Prism, added accordion script
js-tasks-ru/htmlcss-20240614_dkalabukhov pull request #29
Opened 2024-09-25 09:34 UTC by dkalabukhov

2024-09-25 09:35 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-09-28 19:49 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-09-29 07:03 UTC, GSemikozov requested changes

2024-09-29 07:03 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  margin-bottom: 1rem;
марджины на уровне блока не задаем

2024-09-29 07:03 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +  fill: var(--burger-menu-logo);
лучше на уровне иконки currentColor и здесь color

2024-09-29 07:03 UTC, GSemikozov commented on components/header/header.css
> +    margin-top: 41;
а нам точно нужны марджины у хедера?

2024-09-29 07:03 UTC, GSemikozov commented on components/open-menu/open-menu.css
> +  fill: var(--open-menu-icon);
см выше

2024-09-29 07:03 UTC, GSemikozov commented on components/tabs/tabs.css
> +/* Prism */
призм в табах? либо адаптировать классы к блоку табов, либо указывать их в файле стилей с призм

2024-10-06 13:30 UTC, dkalabukhov commented on components/tabs/tabs.css
> +/* Prism */
Исправил, поместил файлы prism в папку prismjs, где дополнительно создал файл prims-fix.css, в котором указал данные правила.

2024-10-06 13:35 UTC, dkalabukhov commented on 07-lection5/04-input/input.css
> +  margin-bottom: 1rem;
Исправил. Задал марджины через родительский элемент: .container-margin-bottom .form-group

2024-10-06 13:44 UTC, dkalabukhov commented on components/header/header.css
> +    margin-top: 41;
Поменял margin на padding. В медиа-запросе  удалил ненужный margin.

2024-10-06 13:48 UTC, dkalabukhov commented on 09-lection7/01-burger-menu/burger-menu.css
> +  fill: var(--burger-menu-logo);
Добавил в css fill: currentColor, там очень много надо менять в html (на всех страницах проекта почти). Так можно решить проблему?

2024-10-06 13:50 UTC, dkalabukhov commented on components/open-menu/open-menu.css
> +  fill: var(--open-menu-icon);
Исправил по аналогии с предыдущим.

2024-10-06 13:58 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-07 09:43 UTC, GSemikozov requested changes

2024-10-07 09:43 UTC, GSemikozov commented on components/container-margin-bottom/container-margin-bottom.css
> +.container-margin-bottom .form-group {
так делать нельзя) в файле блока описываются стили этого блока и его элементов, а не тех блоков, которые встраиваем внутрь. Да и вообще - совершенно неправильно иметь блок который задает марджины - мы же договорились, что при использовании БЭМ на уровне блока марджины не задаем. Как правильно - здесь: https://ru.bem.info/methodology/key-concepts/#%D0%9C%D0%B8%D0%BA%D1%81

2024-10-07 09:43 UTC, GSemikozov commented on components/header/header.css
> +  fill: currentColor;
нет, так не правильно. В svg иконке цвет задается в атрибуте fill - именно там и надо писать currentColor. А здесь тогда - `color: your-color;`

2024-10-30 14:39 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-30 14:43 UTC, dkalabukhov commented on components/header/header.css
> +  fill: currentColor;
Везде исправил

2024-10-30 14:43 UTC, dkalabukhov commented on components/container-margin-bottom/container-margin-bottom.css
> +.container-margin-bottom .form-group {
Исправил

2024-11-12 08:09 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +  fill: var(--burger-menu-logo);
неа, так нельзя решить проблему / так работать не будет. Смысл в том, чтобы в css использовать color, а не fill | stroke

2024-12-05 20:45 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-12-05 20:46 UTC, dkalabukhov commented on 09-lection7/01-burger-menu/burger-menu.css
> +  fill: var(--burger-menu-logo);
Исправил везде на currentColor

2024-12-12 15:14 UTC, GSemikozov approved these changes

2024-12-12 15:14 UTC, merged